// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Load both .env and .env.local files
config({ path: ".env" });
config({ path: ".env.local" });

// 根据 DATABASE_URL 的协议自动选择数据库类型
function getDatabaseProvider(url: string): string {
  if (!url) {
    throw new Error("DATABASE_URL is required");
  }

  if (url.startsWith("mysql://")) {
    return "mysql";
  } else if (url.startsWith("postgresql://") || url.startsWith("postgres://")) {
    return "postgresql";
  } else if (url.startsWith("sqlite://")) {
    return "sqlite";
  } else {
    throw new Error(`Unsupported database protocol in DATABASE_URL: ${url}. Supported: mysql://, postgresql://, postgres://, sqlite://`);
  }
}

const databaseUrl = env("DATABASE_URL");
const provider = getDatabaseProvider(databaseUrl);

// Log the detected provider for debugging
console.log(`🔍 Detected database provider: ${provider} for URL: ${databaseUrl.replace(/:[^:]*@/, ':***@')}`);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
